### ISSUE TITLE
For frame [velodyne]: Frame [velodyne] does not exist

### ISSUE THREAD

**Issue by brett--anderson** [udacity/didi-competition#13]
I tried following the instructions here https://github.com/udacity/didi-competition/blob/master/docs/GettingStarted.md

As per the instructions I downloaded the Didi-Training-Release-1.tar.gz and ran rviz while playing 5mph.bag. In Rviz I could only select ```base_link``` or ```radar``` as the fixed frame, the instructions request selecting ```velodyne``` as the fixed frame, which was not an option. After selecting ```radar```, I tried to add the velodyne point-cloud by topic. After doing this I received the error:

```For frame [velodyne]: Frame [velodyne] does not exist```

I get the same error if I select ```base_link``` as the fixed frame. I'm running ROS Kinetic on Ubuntu 16.04.

**Comment by brett--anderson** [comment]
I'm still seeing the error, but manually typing in velodyne as the Fixed Frame and then add the topic for visualisation seems to display the data correctly.

**Comment by agneevguin** [comment]
Same error for me and manually typing sets it. Is this a bug?

**Comment by thisisjaskaran** [comment]
Was this ever solved?

**Comment by ajay1606** [comment]
Any one solved this ? For frame [velodyne]: Frame [velodyne] does not exist 

Thanks
