### ISSUE TITLE
calibration.tar.gz.torrent no available 

### ISSUE THREAD

**Issue by robert12321** [udacity/didi-competition#15]
Hello,
I'm writing a bachalor thesis about obstacle detection. I would like to run your code. However I cannot download calibration data. Could you share calibration.tar.gz ? Torrent doesn't work, because no seeders.
I would appreciate your help.
Thank you in advance
Regards
Robert Czwartosz

**Comment by drummist180** [comment]
There were reports during the competition that the calibration data may have been incorrect or lacking necessary information. So even if you find it, it might not be very useful. If you have forum access, here's one such report:
https://discussions.udacity.com/t/calibration-matrix-to-project-lidar-points-onto-camera-image/250099

**Comment by robert12321** [comment]
Thank you. Closing the issue.
